PROJECT_PATH=			/Users/dgomez/Workspaces/workspace-2022-zcode/demo-bank-postgres

GROUP_ID =          	com.vobi.bank
PROJECT_NAME =          demo-bank-postgres

DOMAIN_PACKAGE_NAME =   com.vobi.bank.domain

##DATABASE CONNECTION
DRIVER_CLASS=		org.postgresql.Driver
URL=				jdbc:postgresql://127.0.0.1:5432/bank
USER=				postgres
PASSWORD=			postgres
SCHEMA=				public
CATALOG=			null
TABLE_LIST= document_type,customer , account , registered_account,transaction,user_type,users,transaction_type