#PATH
PROJECT_PATH=			/Users/dgomez/Workspaces/workspace-2023-zcode/demo-bank-postgres

#MAVEN
GROUP_ID =          	com.vobi.bank
PROJECT_NAME =          demo-bank-postgres

DOMAIN_PACKAGE_NAME =   com.vobi.bank.domain

##DATABASE CONNECTION POSTGRES
DRIVER_CLASS=			org.postgresql.Driver
URL=					jdbc:postgresql://127.0.0.1:5432/bank
USER=					postgres
PASSWORD=				postgres
SCHEMA=					public
TABLE_LIST= 			document_type,customer , account , registered_account,transaction,user_type,users,transaction_type


##DATABASE CONNECTION POSTGRES
#DRIVER_CLASS=			org.postgresql.Driver
#URL=					jdbc:postgresql://server_ip:5432/database_name
#USER=					postgres
#PASSWORD=				postgres
#SCHEMA=				public
#TABLE_LIST= 			document_type,customer
##To List tables --> SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;


##DATABASE CONNECTION ORACLE
#DRIVER_CLASS=			oracle.jdbc.driver.OracleDriver
#URL=					jdbc:oracle:thin:@//server_ip:1534/database_name
#USER=					PASSPORT
#PASSWORD=				PASSPORT
#SCHEMA=				PASSPORT
#TABLE_LIST= 			document_type,customer
##To List tables --> select table_name from all_tables where owner ='PASSPORT' order by table_name;


##DATABASE CONNECTION MYSQL
#DRIVER_CLASS=			com.mysql.jdbc.Driver
#URL=					jdbc:mysql://server_ip:3306/database_name
#USER=					root
#PASSWORD=				password
#SCHEMA=				public
#CATALOG=				database_name
#TABLE_LIST= 			document_type,customer