#PATH
PROJECT_PATH=           /Users/camilo/Workspaces/Coomeva/Banco/Work2Gether/tmp2
#PROJECT_PATH=           /Users/camilo/Desktop/genBanco
#MAVEN
GROUP_ID =              co.com.bancoomeva.work2gether
PROJECT_NAME =          work2gether-backend

DOMAIN_PACKAGE_NAME =   co.com.bancoomeva.work2gether.domain

##DATABASE CONNECTION POSTGRES
DRIVER_CLASS=			org.postgresql.Driver
URL=					jdbc:postgresql://database-vortexbird.c8dq5oiucrly.us-east-1.rds.amazonaws.com:5432/tmp_zcode
USER=					cdelgado
PASSWORD=				123456
SCHEMA=					public
TABLE_LIST= 			accounting_accounts,intercompany,offices_cost_center


##DATABASE CONNECTION POSTGRES
#DRIVER_CLASS=			org.postgresql.Driver
#URL=					jdbc:postgresql://server_ip:5432/database_name
#USER=					postgres
#PASSWORD=				postgres
#SCHEMA=				public
#TABLE_LIST= 			document_type,customer
##To List tables --> SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;


##DATABASE CONNECTION ORACLE
#DRIVER_CLASS=            oracle.jdbc.driver.OracleDriver
#URL=                    jdbc:oracle:thin:@//10.50.31.36:1525/DESA12C
#USER=                    DELAGENTEAPP
#PASSWORD=                DELAGENTEAPP
#SCHEMA=                    DELAGENTEAPP
#TABLE_LIST=             CDA_REGLA_SERVICIO,CDA_SERVICIO
##To List tables --> select table_name from all_tables where owner ='PASSPORT' order by table_name;


##DATABASE CONNECTION MYSQL
#DRIVER_CLASS=			software.aws.rds.jdbc.mysql.Driver
#URL=					jdbc:mysql://mod-intcontabledb.ctquet2dgpus.us-east-1.rds.amazonaws.com:3306/mod-intcontabledb
#USER=					conficonuser
#PASSWORD=				intcontabledb
#SCHEMA=					public
#CATALOG=				database_name
#TABLE_LIST= 			accouting_account,intercompany,offices_cost_center
